### ISSUE TITLE
server requirements 

### ISSUE THREAD

**Issue by totayma** [l-n-s/wireguard-install#44]
Hello , how much server hardware ( cpu - ram ) need for handle 1 million Simultaneous connections ?

**Comment by netsec** [comment]
I doubt that a setup that large has ever been attempted before, so you likely will be pushing limits when trying. I could find an article on a VPN deployment for 400 clients but judging from the text, the author just relied on rough estimates about how many clients could be run per CPU and lacked some understanding about how his setup would perform.

You would mainly need to consider these two points:

    The bandwidth your data transfers are going to use would need encryption / decryption at the VPN server side, consuming CPU resources

    OpenVPN client connections consume both, memory and CPU resources on the server even when no data is transferred

Any decent PC hardware available today should easily saturate a Gigabit link with Blowfish or AES-128, even $100 embedded devices are capable of rates near 100 Mbps, so CPU bottlenecks due to bandwidth intensity should not be of any concern.

Given the default rekeying interval of 3600 seconds, a number of 1,000,000 clients would mean that the server would need to be able to complete 278 key exchanges per second on average. While a key exchange is a rather CPU-intensive task, you could offload it to dedicated hardware if needed - cryptographic accelerator cards available easily meet and exceed this number of TLS handshakes. And memory restrictions should not bother too much as well - a 64-bit binary should take care of any virtual memory restrictions you would be likely to hit otherwise.

But the real beauty with OpenVPN is that you can scale it out quite easily - simply set up an arbitrary number of OpenVPN servers and make sure your clients are using them (e.g. through DNS round-robin), configure a dynamic routing protocol of your choice (typically this would be RIP due to its simplicity) and your infrastructure would be capable of supporting an arbitrary number of clients as long as you've got enough hardware.

**Comment by totayma** [comment]
i want use load balancing servers for wireguard servers... no problem for this. but i want know how can calculate server requirements ! 
openvpn needs high Resources. 20mhz per Megabits and 5MB per client !

**Comment by l-n-s** [comment]
Please, note that this issue tracker is not a generic wireguard support line, it's for the script issues only. 

Ask this in the official mailing list https://www.wireguard.com/#contact-the-team
